import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio - Sanjana Sampath Kumar",
  description: "Generated by create next app",
  icons: {
    icon: [{
      rel: 'icon',
      url: '/ProfilePhotoNew.ico',
    }, {
      rel: 'shortcut icon',
      url: '/ProfilePhotoNew.ico',
    }],
    apple: {
      rel: 'apple-touch-icon',
      url: '/ProfilePhotoNew.ico',
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
